apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
spec:
  type: NodePort
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007